GameZone/Models/ErrorViewModel.cs
namespace GameZone.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

GameZone/Controllers/GamesController.cs
namespace GameZone.Controllers
{
    public class GamesController : Controller
    {
        private readonly ICategoriesServices _categoriesServices;
        private readonly IDevicesServices _devicesServices;
        private readonly IGameService _gameServices;
        public GamesController(ICategoriesServices categoriesServices, IDevicesServices devicesServices, IGameService gameServices)
        {
            _categoriesServices = categoriesServices;
            _devicesServices = devicesServices;
            _gameServices = gameServices;
        }
        public IActionResult Index()
        {
            var games = _gameServices.GetAll();
            return View(games);
        }
        public IActionResult Details(int id)
        {
            var game = _gameServices.GetById(id);
            if (game is null)
            {
                return NotFound();
            }
            return View(game);
        }
        [HttpGet]
        public IActionResult Create()
        {
            CreateFormViewModel viewModel = new()
            {
                Categories = _categoriesServices.GetSlecteListCategories(),
                Devices = _devicesServices.GetSelectListDevices(),
            };
            return View(viewModel);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateFormViewModel model)
        {
            if (!ModelState.IsValid)
            {
                model.Categories = _categoriesServices.GetSlecteListCategories();
                model.Devices = _devicesServices.GetSelectListDevices();
                return View(model);
            }
            // Save Game 
            // Save Cover to Server
            await _gameServices.Create(model);
            return RedirectToAction(nameof(Index));
        }
        [HttpGet]
        public IActionResult Edit(int id)
        {
            var game = _gameServices.GetById(id);
            if (game is null)
                return NotFound();

            EditGameViewModelForm viewModel = new()
            {
                Id = id,
                Name = game.Name,
                Description = game.Description,
                categoryId = game.categoryId,
                SelectDevices = game.Devices.Select(d => d.DeviceId).ToList(),
                Categories = _categoriesServices.GetSlecteListCategories(),
                Devices = _devicesServices.GetSelectListDevices(),
                CurrentCover = game.Cover,
            };

            return View(viewModel);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(EditGameViewModelForm model)
        {
            if (!ModelState.IsValid)
            {
                model.Categories = _categoriesServices.GetSlecteListCategories();
                model.Devices = _devicesServices.GetSelectListDevices();
                return View(model);
            }

            var game = await _gameServices.Update(model);

            if (game is null)
                return BadRequest();

            return RedirectToAction(nameof(Index));
        }
        [HttpDelete]
        public IActionResult Delete(int id)
        {
            var isDeleted = _gameServices.Delete(id);

            return isDeleted? Ok() : BadRequest();
        }
    }
}

GameZone/Controllers/HomeController.cs
namespace GameZone.Controllers
{
    public class HomeController : Controller
    {
        private readonly IGameService _gameServices;

        public HomeController(IGameService gameServices)
        {
            _gameServices = gameServices;
        }
        public IActionResult Index()
        {
            var games = _gameServices.GetAll();
            return View(games);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

GameZone/Views/Games/Create.cshtml
@model CreateFormViewModel
@{
    ViewData["Title"] = "Add Game";
}
<h5 class="form-header mt-4">
    <i class="bi bi-plus-circle-dotted"></i>
    Add a New Game
</h5>
<form asp-controller="Games" method="post" enctype="multipart/form-data" class="game-formCreate">
    <div class="form-container">
        <div class="form-left">
            <div class="form-group">
                <label asp-for="Name" class="form-label"></label>
                <input type="text" class="form-input" asp-for="Name" placeholder="Game Name">
                <span asp-validation-for="Name" class="form-error"></span>
            </div>
            <div class="form-group">
                <label asp-for="categoryId" class="form-label"></label>
                <select class="form-select" asp-for="categoryId" asp-items="Model.Categories"
                        data-placeholder="Select a Category" data-minimum-results-for-search="Infinity">
                    <option value=""></option>
                </select>
                <span asp-validation-for="categoryId" class="form-error"></span>
            </div>
            <div class="form-group">
                <label asp-for="SelectDevices" class="form-label"></label>
                <select class="form-select" asp-for="SelectDevices" asp-items="Model.Devices"
                        data-placeholder="Select Devices" data-minimum-results-for-search="Infinity">
                    <option></option>
                </select>
                <span asp-validation-for="SelectDevices" class="form-error"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="form-label"></label>
                <textarea asp-for="Description" class="form-textarea" placeholder="Description"></textarea>
                <span asp-validation-for="Description" class="form-error"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cover" class="form-label"></label>
                <input type="file" class="form-input-file" asp-for="Cover" placeholder="Cover"
                       data-rule-extension="@FileStettings.AllowedExtensions.Replace(".",string.Empty)"
                       data-msg-extension="File type not allowed"
                       data-rule-filesize="@FileStettings.MaxFileSizeInBytes"
                       data-msg-filesize="Maximum allowed size is @FileStettings.MaxFileSizeInBytes Bytes">
                <small class="form-helper">Only @FileStettings.AllowedExtensions files allowed, with max size @FileStettings.MaxFileSizeInMB MB.</small>
                <span asp-validation-for="Cover" class="form-error"></span>
            </div>
            <button type="submit" class="form-button">Save</button>
        </div>
        <div class="col-md-6 d-flex align-items-center justify-content-center pt-4">
            <img class="Cover-Preview d-none img-thumbnail" alt="Cover">
        </div>
    </div>
</form>

@section Scripts {
    <partial name="_ValidationScriptsPartial"></partial>
    <script src="~/js/filesize-validator.js" asp-append-version="true"></script>
    <script src="~/js/game-form.js" asp-append-version="true"></script>
}

GameZone/Views/Games/Details.cshtml
@model Game
@{
    ViewData["Title"] = Model.Name;
}
<div class="modern-card border-success rounded-4 mt-5 overflow-hidden">
    <div class="modern-card-body">
        <div class="modern-row">
            <!-- تفاصيل المنتج -->
            <div class="product-info">
                <h3 class="product-title">@Model.Name</h3>
                <p class="product-description">@Model.Description</p>
                <span class="product-category">@Model.category.Name</span>
                <div class="product-devices mt-3">
                    @foreach (var device in Model.Devices)
                    {
                        <i class="@device.Device.Icon device-icon"></i>
                    }
                </div>
            </div>
            <!-- صورة المنتج -->
            <div class="product-image-wrapper">
                <img src="@($"{FileStettings.ImagesPath}/{Model.Cover}")" alt="@Model.Name" class="product-image" />
            </div>
        </div>
    </div>
</div>
    

GameZone/Views/Games/Edit.cshtml
@model EditGameViewModelForm
@{
    ViewData["Title"] = "Edit Game";
}
<h5 class="form-header mt-4">
    <i class="bi bi-plus-circle-dotted"></i>
    Edit  Game
</h5>
<form asp-controller="Games" method="post" enctype="multipart/form-data" class="game-formCreate">
    <div class="form-container">
        <div class="form-left">
            <div class="form-group">
                <label asp-for="Name" class="form-label"></label>
                <input type="text" class="form-input" asp-for="Name" placeholder="Game Name">
                <span asp-validation-for="Name" class="form-error"></span>
            </div>
            <div class="form-group">
                <label asp-for="categoryId" class="form-label"></label>
                <select class="form-select" asp-for="categoryId" asp-items="Model.Categories"
                        data-placeholder="Select a Category" data-minimum-results-for-search="Infinity">
                    <option value=""></option>
                </select>
                <span asp-validation-for="categoryId" class="form-error"></span>
            </div>
            <div class="form-group">
                <label asp-for="SelectDevices" class="form-label"></label>
                <select class="form-select" asp-for="SelectDevices" asp-items="Model.Devices"
                        data-placeholder="Select Devices" data-minimum-results-for-search="Infinity">
                    <option></option>
                </select>
                <span asp-validation-for="SelectDevices" class="form-error"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="form-label"></label>
                <textarea asp-for="Description" class="form-textarea" placeholder="Description"></textarea>
                <span asp-validation-for="Description" class="form-error"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cover" class="form-label"></label>
                <input type="file" class="form-input-file" asp-for="Cover" placeholder="Cover"
                       data-rule-extension="@FileStettings.AllowedExtensions.Replace(".",string.Empty)"
                       data-msg-extension="File type not allowed"
                       data-rule-filesize="@FileStettings.MaxFileSizeInBytes"
                       data-msg-filesize="Maximum allowed size is @FileStettings.MaxFileSizeInBytes Bytes">
                <small class="form-helper">Only @FileStettings.AllowedExtensions files allowed, with max size @FileStettings.MaxFileSizeInMB MB.</small>
                <span asp-validation-for="Cover" class="form-error"></span>
            </div>
            <button type="submit" class="form-button">Save</button>
        </div>
        <div class="col-md-6 d-flex align-items-center justify-content-center pt-4">
            <img class="Cover-Preview  img-thumbnail" alt="Cover" src="@($"{FileStettings.ImagesPath}/{Model.CurrentCover}")">
        </div>
    </div>
</form>

@section Scripts {
    <partial name="_ValidationScriptsPartial"></partial>
    <script src="~/js/filesize-validator.js" asp-append-version="true"></script>
    <script src="~/js/game-form.js" asp-append-version="true"></script>
}

GameZone/Views/Games/Index.cshtml
@model IEnumerable<Game>
@{
    ViewData["Title"] = "Games";
}
<a class="btn btn-secondary btn-lg mb-3 add-game-btn" asp-action="Create" asp-controller="Games">
    <i class="bi bi-plus-circle-dotted"></i>
    Add Game
</a>

@if (!Model.Any())
{
    <div class="alert alert-warning alert-no-games mt-5">
        <h4 class="alert-heading">No Games!</h4>
        <p class="mb-0"> No Games Were Added yet.</p>
    </div>
}
else
{
    <table class="table table-bordered table-hover games-table">
        <thead class="table-dark">
            <tr>
                <th>Cover</th>
                <th>Name</th>
                <th>Category</th>
                <th>Devices</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var game in Model)
            {
                <tr>
                    <!-- صورة الغلاف -->
                    <td style="width: 15%;">
                        <div class="game-cover" style="background-image: url(@($"{FileStettings.ImagesPath}/{game.Cover}"));"></div>
                    </td>
                    <!-- اسم اللعبة -->
                    <td>
                        <h5 class="game-name">@game.Name</h5>
                    </td>
                    <!-- فئة اللعبة -->
                    <td>
                        <span class="badge game-category">@game.category.Name</span>
                    </td>
                    <!-- الأجهزة -->
                    <td>
                        <div class="devices">
                            @foreach (var gamedevice in game.Devices)
                            {
                                <i class="@gamedevice.Device.Icon device-icon"></i>
                            }
                        </div>
                    </td>
                    <!-- الأزرار -->
                    <td class="text-center table-actions">
                        <!-- زر التعديل -->
                        <a class="btn btn-primary btn-sm me-2" asp-action="Edit" asp-route-id="@game.Id">Edit</a>
                        <!-- زر الحذف -->
                        <a class="btn btn-danger btn-sm js-delete" data-id="@game.Id">Delete</a>

                    </td>
                </tr>
            }
        </tbody>
    </table>
}
@section Scripts{
    <script src="~/js/gamesdelete.js " asp-append-version="true"></script>
}

GameZone/Views/Home/Index.cshtml
@model IEnumerable<Game>
@{
    ViewData["Title"] = "Home Page";
}
@if (!Model.Any())
{
    <div class="alert alert-warning mt-5">
        <h4 class="alert-heading">No Games!</h4>
        <p class="mb-0"> No Games Were Added yet.</p>
    </div>
}
else
{
    <div class="row mt-5">
        @foreach (var game in Model)
        {
            <div class="col-lg-4 col-md-6 mb-4">
                <!-- بطاقة اللعبة -->
                <a class="game-card-link text-decoration-none" asp-controller="Games" asp-action="Details" asp-route-id="@game.Id">
                    <!-- صورة الغلاف -->
                    <div class="game-card-image"
                         style="background-image: url(@($"{FileStettings.ImagesPath}/{game.Cover}"))" alt="@game.Name">
                        <!-- فئة اللعبة -->
                        <div class="game-card-category">
                            <span class="badge game-card-badge">
                                @game.category.Name
                            </span>
                        </div>
                    </div>
                    <!-- اسم اللعبة والأجهزة -->
                    <div class="game-card-details">
                        <h5 class="game-card-title">@game.Name</h5>
                        <div class="game-card-platform-icons">
                            @foreach (var gamedevice in game.Devices)
                            {
                                <i class="@gamedevice.Device.Icon"></i>
                            }
                        </div>
                    </div>
                </a>
            </div>
        }
    </div>
}

GameZone/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>GameZone - @ViewData["Title"] </title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap">
    <link rel="stylesheet" href="~/lib/bootstrap-icons/font/bootstrap-icons.min.css" />
    <link rel ="stylesheet" href="~/css/bootstrap.min.css" />
    <link href="~/lib/select2/css/select2.min.css" rel="stylesheet" />
    <link href="~/lib/sweetalert2/sweetalert2.min.css" rel="stylesheet" />
    <link href="~/css/cssfilecreate.css" rel="stylesheet" />
    <link href="~/css/cssdetailsgames.css" rel="stylesheet" />
    <link href="~/css/cssindexformgame.css" rel="stylesheet" />
    <link href="~/css/cssshomecontroller.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/GameZone.styles.css" asp-append-version="true" />
</head>
<body >
    <header>
        <nav class="navbar navbar-expand-lg bg-dark navbar-custom ">
            <div class="container-fluid">
                <a class="navbar-brand text-white" asp-controller="Home" asp-action="Index">GameZone</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <!-- استخدام <ul> بدلاً من <div> -->
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-controller="Games" asp-action="Index">Games</a>
                        </li>
                    </ul>
                    <ul class="navbar-nav ms-auto">
                        <!-- استخدم <ul> هنا أيضًا -->
                        <li class="nav-item">
                            <a class="nav-link text-white" href="#">Contact</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <main role="main" class="flex-grow-1">
        @RenderBody()
    </main>

    <footer class="footer">
        <div class="container">
            &copy; 2024 - GameZone - <a asp-area="" asp-controller="Home" asp-action="Index">GameZone</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/select2/js/select2.min.js"></script>
    <script src="~/lib/sweetalert2/sweetalert2.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>